services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: [ "CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/api/hello', timeout=3)" ]
      interval: 5s
      timeout: 3s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy